apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "challenger.fullname" . }}-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "challenger.fullname" . }}-test
subjects:
- kind: ServiceAccount
  name: {{ include "challenger.fullname" . }}-test
