apiVersion: v1
kind: Service
metadata:
  name: {{ include "beacons.fullname" . }}
  labels:
    {{- include "beacons.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.p2pPort }}
      targetPort: p2p-tcp
      protocol: TCP
      name: p2p-tcp
    - port: {{ .Values.p2pPort }}
      targetPort: p2p-udp
      protocol: UDP
      name: p2p-udp
    - port: {{ .Values.httpPort }}
      targetPort: http-api
      protocol: TCP
      name: http-api
    - port: {{ .Values.rpcPort }}
      targetPort: rpc
      protocol: TCP
      name: rpc
    - port: {{ .Values.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  {{- if .Values.extraPorts }}
    {{ toYaml .Values.extraPorts | nindent 4}}
  {{- end }}
  selector:
    {{- include "beacons.selectorLabels" . | nindent 4 }}
