{{- /*
Create a configmap to hold the erpc.yaml configuration.
*/}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "erpc.fullname" . }}-config
  labels:
    {{- include "erpc.labels" . | nindent 4 }}
data:
  erpc.yaml: |
    {{- .Values.erpc | toYaml | nindent 4 }}
