apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "erpc.fullname" . }}-config
data:
  erpc.yaml: |
    logLevel: warn
    {{ if .Values.erpc.cacheConfig }}
    database:
      evmJsonRpcCache:
        {{- .Values.erpc.cacheConfig | toYaml | nindent 8 }}
    {{- end }}

    server:
      httpHost: 0.0.0.0
      httpPort: {{ .Values.service.ports.http.port | default "4000" }}

    metrics:
      enabled: true
      host: 0.0.0.0
      port: {{ .Values.service.ports.metrics.port | default "4001" }}

    projects:
      {{- range $project := .Values.erpc.projects }}
      - id: {{ $project.id }}
        networks:
        {{- range $project.networkIds }}
          - architecture: evm
            evm:
              chainId: {{ . }}
            failsafe:
              timeout:
                duration: 30s
              retry:
                maxCount: 3
                delay: 500ms
                backoffMaxDelay: 10s
                backoffFactor: 0.3
                jitter: 500ms
              hedge:
                delay: 3000ms
                maxCount: 2
          {{- end }}
      {{- end }}
        upstreams:
        {{- range $upstream := .Values.erpc.upstreams }}
          - id: {{ $upstream.id }}
            endpoint: {{ $upstream.endpoint }}
            rateLimitBudget: {{ $upstream.rateLimit }}
            evm:
              chainId: {{ $upstream.chainId }}
            failsafe:
              timeout:
                duration: 15s
              retry:
                maxCount: 2
                delay: 1000ms
                backoffMaxDelay: 10s
                backoffFactor: 0.3
                jitter: 500ms
        {{- end }}

    rateLimiters:
      budgets:
        {{- range $rateLimiter := .Values.erpc.rateLimiters }}
        - id: {{ $rateLimiter.id }}
          rules:
          {{- range $rateLimiter.rules }}
            - method: {{ .method | quote }}
              maxCount: {{ .maxCount }}
              period: {{ .period }}
          {{- end }}
        {{- end }}
