apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "erpc.fullname" . }}-config
data:
  erpc.yaml: |
    logLevel: warn
    {{ if .Values.erpc.cacheConfig }}
    database:
      evmJsonRpcCache:
        {{- .Values.erpc.cacheConfig | toYaml | nindent 8 }}
    {{- end }}

    server:
      httpHost: 0.0.0.0
      httpPort: {{ .Values.service.ports.http.port | default "4000" }}

    metrics:
      enabled: true
      host: 0.0.0.0
      port: {{ .Values.service.ports.metrics.port | default "4001" }}

    projects:
      {{- range $project := .Values.erpc.projects }}
      - id: {{ $project.id }}
        networks:
        {{- range $project.networkIds }}
          - architecture: evm
            evm:
              chainId: {{ . }}
            {{- if $project.failsafe }}
            failsafe:
              {{- $project.failsafe | toYaml | nindent 14 }}
            {{- end }}
          {{- end }}

        upstreams:
        {{- range $upstream := $project.upstreams }}
          - id: {{ $upstream.id }}
            endpoint: {{ $upstream.endpoint }}
            rateLimitBudget: {{ $upstream.rateLimit }}
            {{- if $upstream.chainId }}
            evm:
              chainId: {{ $upstream.chainId }}
            {{- end }}
            {{- if $upstream.failsafe }}
            failsafe:
              {{- $upstream.failsafe | toYaml | nindent 14 }}
            {{- end }}
        {{- end }}
      {{- end }}

    rateLimiters:
      budgets:
        {{- range $rateLimiter := .Values.erpc.rateLimiters }}
        - id: {{ $rateLimiter.id }}
          rules:
          {{- range $rateLimiter.rules }}
            - method: {{ .method | quote }}
              maxCount: {{ .maxCount }}
              period: {{ .period }}
          {{- end }}
        {{- end }}
