apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "erpc.fullname" . }}-config
data:
  erpc.yaml: |
    logLevel: {{ .Values.erpc.logLevel | default "warn" }}
    {{- if .Values.erpc.cacheConfig }}
    database:
      {{- if .Values.erpc.sharedState }}
      sharedState:
        {{- .Values.erpc.sharedState | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.erpc.disableCache }}
      evmJsonRpcCache: ~
      {{- else }}
      evmJsonRpcCache:
        {{- .Values.erpc.cacheConfig | toYaml | nindent 8 }}
      {{- end }}
    {{- end }}

    {{ if .Values.erpc.admin }}
    admin:
      {{- .Values.erpc.admin | toYaml | nindent 6 }}
    {{- end }}

    server:
      {{- .Values.erpc.server | toYaml | nindent 6 }}

    metrics:
      {{- .Values.erpc.metrics | toYaml | nindent 6 }}

    projects:
      {{- range $project := .Values.erpc.projects }}
      - id: {{ $project.id }}
        {{- if $project.authStrategies }}
        auth:
          strategies:
          {{- range $strategy := $project.authStrategies }}
            - {{ $strategy | toYaml | nindent 14 | trim }}
          {{- end }}
        {{- end }}
        {{- if $project.providers }}
        providers:
          {{- $project.providers | toYaml | nindent 10 }}
        {{- end }}
        {{- if $project.networkDefaults }}
        networkDefaults:
          {{- $project.networkDefaults | toYaml | nindent 10 }}
        {{- end }}
        networks:
        {{- range $project.networkIds }}
          - architecture: evm
            evm:
              chainId: {{ . }}
            {{- if $project.networkFailsafe }}
            failsafe:
              {{- $project.networkFailsafe | toYaml | nindent 14 }}
            {{- end }}
            {{- if $project.selectionPolicy }}
            selectionPolicy:
              {{- $project.selectionPolicy | toYaml | nindent 14 }}
            {{- end }}
          {{- end }}
        {{- if $project.upstreamDefaults }}
        upstreamDefaults:
          {{- $project.upstreamDefaults | toYaml | nindent 10 }}
        {{- end }}
        upstreams:
        {{- range $upstream := $project.upstreams }}
          - id: {{ $upstream.id }}
            endpoint: {{ $upstream.endpoint }}
            rateLimitBudget: {{ $upstream.rateLimitBudget }}
            {{- if $upstream.evm }}
            evm:
              {{- $upstream.evm | toYaml | nindent 14 }}
            {{- end }}
              {{- if $upstream.statePollerInterval }}
              statePollerInterval: {{ $upstream.statePollerInterval }}
              {{- end }}
              {{- if $upstream.nodeType }}
              nodeType: {{ $upstream.nodeType }}
              {{- end }}
              {{- if $upstream.maxAvailableRecentBlocks }}
              maxAvailableRecentBlocks: {{ $upstream.maxAvailableRecentBlocks  }}
              {{- end }}
              {{- if $upstream.getLogsMaxBlockRange }}
              getLogsMaxBlockRange: {{ $upstream.getLogsMaxBlockRange  }}
              {{- end }}
            {{- if $upstream.group }}
            group: {{ $upstream.group }}
            {{- end }}
            {{- if $upstream.failsafe }}
            failsafe:
              {{- $upstream.failsafe | toYaml | nindent 14 }}
            {{- end }}
            {{- if $upstream.rateLimitAutoTune }}
            rateLimitAutoTune:
              {{- $upstream.rateLimitAutoTune | toYaml | nindent 14 }}
            {{- end }}
            {{- if $upstream.jsonRpc }}
            jsonRpc:
              {{- $upstream.jsonRpc | toYaml | nindent 14 }}
            {{- end }}
            {{- if $upstream.ignoreMethods }}
            ignoreMethods:
              {{- $upstream.ignoreMethods | toYaml | nindent 14 }}
            {{- end }}
            {{- if $upstream.allowMethods }}
            allowMethods:
              {{- $upstream.allowMethods | toYaml | nindent 14 }}
            {{- end }}
            {{- if $upstream.autoIgnoreUnsupportedMethods }}
            autoIgnoreUnsupportedMethods: {{ $upstream.autoIgnoreUnsupportedMethods | default "true" }}
            {{- end }}
        {{- end }}
      {{- end }}

    rateLimiters:
      budgets:
        {{- range $rateLimiter := .Values.erpc.rateLimiters }}
        - id: {{ $rateLimiter.id }}
          rules:
          {{- range $rateLimiter.rules }}
            - method: {{ .method | quote }}
              maxCount: {{ .maxCount }}
              period: {{ .period }}
          {{- end }}
        {{- end }}
