apiVersion: v1
kind: Service
metadata:
  name: {{ include "erpc.fullname" . }}-headless
  labels:
    {{- include "erpc.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
  {{- with .Values.service.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.ports.http.port }}
      targetPort: {{ .Values.service.ports.http.port }}
      protocol: {{ .Values.service.ports.http.protocol }}
      name: http
  selector:
    {{- include "erpc.selectorLabels" . | nindent 4 }}
