apiVersion: v1
kind: Service
metadata:
  name: {{ include "erpc.fullname" . }}-headless
  labels:
    {{- include "erpc.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
  {{- with .Values.service.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    {{- range $key, $val := .Values.service.ports }}
    - port: {{ $val.port }}
      targetPort: {{ $val.port }}
      protocol: {{ $val.protocol }}
      name: {{ $key }}
    {{- end }}
  selector:
    {{- include "erpc.selectorLabels" . | nindent 4 }}
