apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "omnia-feed.fullname" . }}-config
data:
  ### note this config is only suitable for eth goerli as per https://github.com/chronicleprotocol/omnia-feed/blob/master/omnia/config/relay-ethereum-goerli.json
  omnia.json: |-
    {
      "mode": "feed",
      {{- if .Values.keystore.enabled }}
      "ethereum": {
        "from": "{{ .Values.keystore.ethFromAddress }}",
        "keystore": "/keystore/",
        "password": "/password/password.txt",
        "network": "{{ .Values.ethereum.ethRpc }}",
        "gasPrice": {
          "multiplier": 1,
          "source": "node"
        }
      },
      {{- end }}
      "options": {
        "debug": true,
        "goferConfig": "",
        "interval": 60,
        "logFormat": "text",
        "msgLimit": 35,
        "setzerCacheExpiry": 120,
        "setzerMinMedian": 3,
        "setzerTimeout": 10,
        "spireConfig": "",
        "srcTimeout": 10,
        "verbose": true,
        "ethGas": 200000,
        "chainType": "ethereum"
      },
      {{- if .Values.omniaConfig.transports }}
      "transports": {{ toJson .Values.omniaConfig.transports }},
      {{ else }}
      "transports": ["spire"],
      {{- end }}
      {{- if .Values.omniaConfig.scuttlebotIdMap }}
      "scuttlebotIdMap": {
        {{- $keys := .Values.omniaConfig.scuttlebotIdMap | keys | sortAlpha }}
        {{- range $i, $key := $keys }}
        "{{ $key }}": "{{ index $.Values.omniaConfig.scuttlebotIdMap $key }}"{{ if not (eq $i (sub (len $keys) 1)) }},{{ end }}
        {{- end }}
      },
      {{- end }}
      "pairs": {
        {{- if .Values.omniaConfig.pairs }}
        {{- range .Values.omniaConfig.pairs }}
        "{{ .name }}": {
          "msgExpiration": {{ .expiration }},
          "msgSpread": {{ .spread }}
        }{{ if not (eq .name (index (last $.Values.omniaConfig.pairs) "name")) }},{{ end }}
        {{- end }}
        {{ else }}
        "BTC/USD":{"msgExpiration":1800,"msgSpread":0.5},
        "ETH/BTC":{"msgExpiration":1800,"msgSpread":0.5},
        "ETH/USD":{"msgExpiration":1800,"msgSpread":0.5},
        "GNO/USD":{"msgExpiration":1800,"msgSpread":0.5},
        "IBTA/USD":{"msgExpiration":3600,"msgSpread":1},
        "LINK/USD":{"msgExpiration":1800,"msgSpread":0.5},
        "MANA/USD":{"msgExpiration":1800,"msgSpread":0.5},
        "MATIC/USD":{"msgExpiration":1800,"msgSpread":0.5},
        "MKR/USD":{"msgExpiration":1800,"msgSpread":0.5},
        "RETH/USD":{"msgExpiration":1800,"msgSpread":0.5},
        "WSTETH/USD":{"msgExpiration":1800,"msgSpread":0.5},
        "YFI/USD":{"msgExpiration":1800,"msgSpread":0.5}
      {{- end }}
      }
    }
  spire.json: |-
    {{- if .Values.omniaConfig.spireJson }}
    {{ .Values.omniaConfig.spireJson | nindent 4 }}
    {{ else }}
    {
      "spire": {
        "rpc": {
          "address": "feed-spire:9100"
        },
      }
    }
    {{- end }}
