apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "omnia-feed.fullname" . }}-config
data:
  omnia.json: |-
    {
      {{- if .Values.keystore.enabled }}
      "ethereum": {
        "from": "{{ .Values.keystore.ethFromAddress }}",
        "keystore": "/keystore/",
        "password": "/password/password.txt",
        "network": "",
        "type": "ethereum"
      },
      {{- end }}
      {{- .Values.omniaConfig | nindent 6 }}
    }
