apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "omnia-feed.fullname" . }}
  labels:
    {{- include "omnia-feed.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "omnia-feed.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "omnia-feed.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "omnia-feed.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # command: ["sleep", "infinity"]
          ports:
          {{- range $key, $val := .Values.service.ports }}
            - name: {{ $key }}
              containerPort: {{ $val.port }}
              protocol: {{ $val.protocol }}
          {{- end }}
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          env:
          - name: OMNIA_CONFIG
            value: /config/omnia/omnia.json
          - name: SPIRE_CONFIG
            value: /config/spire/config.hcl
          - name: GOFER_CONFIG
            value: /config/gofer/gofer.hcl
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: omnia
            mountPath: /home/omnia/
          - name: config
            mountPath: /config/omnia/
          - name: gofer
            mountPath: /config/gofer/
          - name: spire
            mountPath: /config/spire/
          {{- if .Values.keystore.enabled }}
          - name: keystore
            mountPath: /keystore/
          - name: password
            mountPath: /password/
          {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ include "omnia-feed.fullname" . }}-config
      - name: omnia
        emptyDir: {}
      - name: spire
        configMap:
          name: {{ .Release.Name }}-gofer-config
          items:
          - key: gofer.hcl
            path: gofer.hcl
      - name: gofer
        configMap:
          name: {{ .Release.Name }}-spire-config
          items:
          - key: spire.hcl
            path: spire.hcl
      {{- if .Values.keystore.enabled }}
      - name: keystore
        configMap:
          name: {{ include "omnia-feed.fullname" . }}-keystore
          items:
          - key: keystore.json
            path: keystore.json
      - name: password
        configMap:
          name: {{ include "omnia-feed.fullname" . }}-keystore
          items:
          - key: password.txt
            path: password.txt
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
