repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    # -   id: check-yaml
    -   id: check-added-large-files
- repo: https://github.com/chronicleprotocol/charts/
  rev: precommit-hooks-0.0.1
  hooks:
    - id: helm-docs
      args: []
    - id: chart-lint
      args: []