# Default values for mantle.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

# -- Download from snapshot. will run snapshot sync before starting node in an initContainer. refer to https://github.com/mantlenetworkio/networks/blob/main/run-node-mainnet.md#download-latest-snapshot-from-mantle
snapShotSync:
  enabled: false
  snapShotUrl: 'https://s3.ap-southeast-1.amazonaws.com/snapshot.mantle.xyz'
  tarballName: '20240117-mainnet-chaindata.tar'

# -- Path to store data
data:
  path: /root/.ethereum/geth

# -- ETH l1 node
ethL1: "https://rpc.ankr.com/eth"
# -- DLT service url refer to https://docs.mantle.xyz/network/for-validators/deploy-a-node/deploying-a-rollup-verifier-replica-node#network-dtl-url
rollUpClientHttp: "https://dtl.mantle.xyz"
rollUpStateDumpPath: "https://mantlenetworkio.github.io/networks/mainnet/genesis.json"

sequencerClientHttp: "https://rpc.mantle.xyz"
blockSignerAddress: "0x000000b36A00872bAF079426e012Cf5Cd2A74E8b"
blockSignerKey: "9f50ccaebd966113a0ef09793f8a3288cd0bb2c05d20caa3c0015b4e665f1b2d"

# -- Network id
networkId: 5000
# -- Chain Id
chainId: 5000

env:
  - name: ETH1_SYNC_SERVICE_ENABLE
    value: "true"
  - name: GASPRICE
    value: "0"
  - name: RPC_ENABLE
    value: "true"
  - name: IPC_DISABLE
    value: "true"
  - name: ROLLUP_BACKEND
    value: "l2"
  - name: ROLLUP_ENABLE_L2_GAS_POLLING
    value: "true"
  - name: ROLLUP_ENFORCE_FEES
    value: "true"
  - name: RPC_API
    value: "eth,net,rollup,web3"
  - name: RPC_CORS_DOMAIN
    value: "*"
  - name: TARGET_GAS_LIMIT
    value: "30000000"
  - name: ROLLUP_FEE_THRESHOLD_DOWN
    value: "1"
  - name: ROLLUP_TIMESTAMP_REFRESH
    value: "5s"
  - name: ETH1_CTC_DEPLOYMENT_HEIGHT
    value: "8"
  - name: RETRIES
    value: "60"
  - name: NO_DISCOVER
    value: "true"
  - name: NO_USB
    value: "true"
  - name: GCMODE
    value: "archive"
  - name: RPC_VHOSTS
    value: "*"
  - name: ETH1_CONFIRMATION_DEPTH
    value: "0"
  - name: USING_BVM
    value: "true"
  - name: ROLLUP_POLL_INTERVAL_FLAG
    value: "500ms"
  - name: VERBOSITY
    value: "3"
  - name: WS_PORT
    value: "8546"
  - name: WS_ADDR
    value: "0.0.0.0"
  - name: WS
    value: "true"
  - name: WS_ORIGINS
    value: "*"
  - name: RPC_ADDR
    value: "0.0.0.0"
  - name: ROLLUP_VERIFIER_ENABLE
    value: "true"
  - name: ROLLUP_FEE_THRESHOLD_UP
    value: "4000"
  - name: WS_API
    value: "eth,net,rollup,web3"

image:
  repository: mantlenetworkio/l2geth
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  ports:
    httprpc:
      port: 8545
      protocol: TCP
    wsrpc:
      port: 8546
      protocol: TCP


# @default -- See `values.yaml`
livenessProbe:
  tcpSocket:
    port: httprpc
  initialDelaySeconds: 60
  periodSeconds: 120

# @default -- See `values.yaml`
readinessProbe:
  tcpSocket:
    port: httprpc
  initialDelaySeconds: 10
  periodSeconds: 10

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

persistence:
  # -- Uses an EmptyDir when not enabled
  enabled: false
  # -- Use an existing PVC when persistence.enabled
  existingClaim: null
  # -- Access mode for the volume claim template
  accessModes:
  - ReadWriteOnce
  # -- Requested size for volume claim template
  size: 1600Gi
  # -- Use a specific storage class
  # E.g 'local-path' for local storage to achieve best performance
  # Read more (https://github.com/rancher/local-path-provisioner)
  storageClassName: null
  # -- Annotations for volume claim template
  annotations: {}
  # -- Selector for volume claim template
  selector: {}
  #   matchLabels:
  #     app.kubernetes.io/name: something

serviceMonitor:
  # -- If true, a ServiceMonitor CRD is created for a prometheus operator
  # https://github.com/coreos/prometheus-operator
  enabled: false
  # -- Path to scrape
  path: /debug/metrics
  # -- Alternative namespace for ServiceMonitor
  namespace: null
  # -- Additional ServiceMonitor labels
  labels: {}
  # -- Additional ServiceMonitor annotations
  annotations: {}
  # -- ServiceMonitor scrape interval
  interval: 1m
  # -- ServiceMonitor scheme
  scheme: http
  # -- ServiceMonitor TLS configuration
  tlsConfig: {}
  # -- ServiceMonitor scrape timeout
  scrapeTimeout: 30s
  # -- ServiceMonitor relabelings
  relabelings: []

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []
affinity: {}
