apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "omnia-relay.fullname" . }}-config
data:
  omnia.json: |-
    {
      {{- if .Values.keystore.enabled }}
      "ethereum": {
        "from": "{{ .Values.keystore.ethFromAddress }}",
        "keystore": "/keystore/",
        "password": "/password/password.txt",
        "network": "{{ .Values.ethereum.ethRpc }}",
        "type": "{{ .Values.ethereum.networkType }}"
      },
      {{- end }}
      {{- .Values.omniaConfig | nindent 6 }}
    }
