apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "omnia-relay.fullname" . }}
  labels:
    {{- include "omnia-relay.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "omnia-relay.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "omnia-relay.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "omnia-relay.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{ if .Values.omniaConfig.sleep }}
          command: ["sleep", "infinity"]
          {{ end }}
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          env:
          {{- include "helpers.list-env-variables" . | indent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: config
            mountPath: /config/omnia/
          - name: keystore
            mountPath: /keystore/keystore.json
            subPath: keystore.json
          - name: password
            mountPath: /keystore/password.txt
            subPath: password.txt
          {{- if index .Values "ssb-server" "enabled"}}
          - name: ssb-config
            mountPath: /home/omnia/.ssb/
          {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ include "omnia-relay.fullname" . }}-config
      {{- if index .Values "ssb-server" "enabled"}}
      - name: ssb-config
        configMap:
          name: {{ .Release.Name }}-ssb-server-config
      {{- end }}
      {{- if .Values.keystore.enabled }}
      {{- if .Values.keystore.existingSecret }}
      - name: keystore
        secret:
          secretName: {{ .Values.keystore.existingSecret }}
          items:
          - key: keystoreFile
            path: keystore.json
      - name: password
        secret:
          secretName: {{ .Values.keystore.existingSecret }}
          items:
          - key: password.txt
            path: password.txt
      {{- else }}
      - name: keystore
        configMap:
          name: {{ include "omnia-relay.fullname" . }}-keystore
          items:
          - key: keystore.json
            path: keystore.json
      - name: password
        configMap:
          name: {{ include "omnia-relay.fullname" . }}-keystore
          items:
          - key: password.txt
            path: password.txt
      {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
