# Default values for ghost.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/chronicleprotocol/ghost
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

logLevel: null
logFormat: null

# Provide ETH keys from existing secrets
# use only existing secret OR env vars, do not provide both
ethConfig: {}
  # ethFrom:
  #   existingSecret: ""
  #   key: ""
  # ethKeys:
  #   existingSecret: ""
  #   key: ""
  # ethPass:
  #   existingSecret: ""
  #   key: ""
# Environment variable listing
env: {}
  # non sensitive variables
  # refer to https://github.com/chronicleprotocol/oracle-suite/tree/master/cmd/spire#environment-variables
  # normal:
  #   CFG_FEEDS: ""
  #   CFG_LIBP2P_BOOTSTRAP_ADDRS: "/dns4/spire/tcp/8000/p2p/"
  #   CFG_GOFER_OPENEXCHANGERATES_API_KEY:
  #   CFG_WEBAPI_ENABLE: 0
  #   # Provide ETH keys as env vars
  #   CFG_ETH_FROM: ""
  #   CFG_ETH_PASS: ""
  #   CFG_ETH_KEYS: ''


# Environment variable listing

# ethereum RPC client
# exposes CFG_ETH_RPC_URLS, CFG_ETH_CHAIN_ID  as env vars
ethRpcUrl: null
ethChainId: null

# default RPC client
# exposes CFG_RPC_URLS, CFG_CHAIN_ID as env vars
rpcUrl: null
chainId: null

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  ports:
    libp2p:
      port: 8000
      protocol: TCP
    ### to add more port-mappings, add them here:
    # rpc:
    #   port: 9100
    #   protocol: TCP

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# -- Extra K8s manifests to deploy
extraObjects: []
  # - apiVersion: "kubernetes-client.io/v1"
  #   kind: ExternalSecret
  #   metadata:
  #     name: some-secrets
  #   spec:
  #     backendType: someBackend
  #     data:
  #       - key: some-creds
  #         name: client_secret
