{{- if .Values.gossipOverride }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: gossip-override
data:
  override_gossip_config.json: |
    { "root_node_ips": [{"Ip": "20.188.6.225"}, {"Ip": "74.226.182.22"}, {"Ip": "57.182.103.24"}, {"Ip": "3.115.170.40"}, {"Ip": "46.105.222.166"}, {"Ip": "91.134.41.52"}], "try_new_peers": false, "chain": "Mainnet" }
{{- end }}
