apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "gofer.fullname" . }}-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "services"]
  verbs: ["get", "list"]
