apiVersion: v1
kind: Service
metadata:
  name: {{ include "gofer.fullname" . }}
  labels:
    {{- include "gofer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: listener
      protocol: TCP
      name: listener
  selector:
    {{- include "gofer.selectorLabels" . | nindent 4 }}
