# Default values for base.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

# -- Download from snapshot. will run snapshot sync before starting node in an initContainer. refer to https://docs.base.org/guides/run-a-base-node/#snapshots
snapShotSync:
  enabled: false
  snapShotUrl: "https://base-snapshots-mainnet-archive.s3.amazonaws.com/$(curl https://base-snapshots-mainnet-archive.s3.amazonaws.com/latest)"

# For testnet values, refer to https://github.com/base-org/node/blob/main/.env.sepolia

# -- Network id. Defaults to mainnet value.
networkId: base-mainnet
# -- Auth token. Defaults to hardcoded value.
jwtSecret: 688f5d737bad920bdfb2fc2f488d6b6209eebda1dae949a8de91398d932c517a

geth:
  # -- Genesis file path. Defaults to mainnet value.
  genesisFilePath: mainnet/genesis-l2.json
  # -- List of boot nodes for geth. Defaults to mainnet value.
  bootNodes: enode://87a32fd13bd596b2ffca97020e31aef4ddcc1bbd4b95bb633d16c1329f654f34049ed240a36b449fda5e5225d70fe40bc667f53c304b71f8e68fc9d448690b51@3.231.138.188:30301,enode://ca21ea8f176adb2e229ce2d700830c844af0ea941a1d8152a9513b966fe525e809c3a6c73a2c18a12b74ed6ec4380edf91662778fe0b79f6a591236e49e176f9@184.72.129.189:30301,enode://acf4507a211ba7c1e52cdf4eef62cdc3c32e7c9c47998954f7ba024026f9a6b2150cd3f0b734d9c78e507ab70d59ba61dfe5c45e1078c7ad0775fb251d7735a2@3.220.145.177:30301,enode://8a5a5006159bf079d06a04e5eceab2a1ce6e0f721875b2a9c96905336219dbe14203d38f70f3754686a6324f786c2f9852d8c0dd3adac2d080f4db35efc678c5@3.231.11.52:30301,enode://cdadbe835308ad3557f9a1de8db411da1a260a98f8421d62da90e71da66e55e98aaa8e90aa7ce01b408a54e4bd2253d701218081ded3dbe5efbbc7b41d7cef79@54.198.153.150:30301
  # -- URL of the sequencer. Defaults to mainnet value.
  sequencerHttp: https://mainnet-sequencer.base.org

  resources: {}

  securityContext: {}

  service:
    type: ClusterIP
    ports:
      rpc:
        port: 8545
        protocol: TCP
      ws:
        port: 8546
        protocol: TCP
      # p2p:
      #   port: 30303
      #   protocol: TCP
      # p2pudp:
      #   port: 30303
      #   protocol: UDP
      metrics:
        port: 7060
        protocol: TCP

  # @default -- See `values.yaml`
  livenessProbe:
    tcpSocket:
      port: rpc
    initialDelaySeconds: 60
    periodSeconds: 120

  # @default -- See `values.yaml`
  readinessProbe:
    tcpSocket:
      port: rpc
    initialDelaySeconds: 10
    periodSeconds: 10

opNode:
  # -- Boolean wheter to trust L1 RPC. Defaults to true.
  l1TrustRpc: "true"
  # -- L1 RPC URL. Defaults to mainnet value.
  l1EthRpc: http://eth-mainnet-dev-ethereum.eth-mainnet-dev.svc.cluster.local:8545
  # -- L1 Beacon URL. Defaults to mainnet value.
  l1Beacon: http://beacon-prysm-mainnet-beacons.beacon-prysm-mainnet.svc.cluster.local:3500
  # -- List of OP Node P2P boot nodes. Defaults to mainnet value.
  p2pBootNodes: enr:-J24QNz9lbrKbN4iSmmjtnr7SjUMk4zB7f1krHZcTZx-JRKZd0kA2gjufUROD6T3sOWDVDnFJRvqBBo62zuF-hYCohOGAYiOoEyEgmlkgnY0gmlwhAPniryHb3BzdGFja4OFQgCJc2VjcDI1NmsxoQKNVFlCxh_B-716tTs-h1vMzZkSs1FTu_OYTNjgufplG4N0Y3CCJAaDdWRwgiQG,enr:-J24QH-f1wt99sfpHy4c0QJM-NfmsIfmlLAMMcgZCUEgKG_BBYFc6FwYgaMJMQN5dsRBJApIok0jFn-9CS842lGpLmqGAYiOoDRAgmlkgnY0gmlwhLhIgb2Hb3BzdGFja4OFQgCJc2VjcDI1NmsxoQJ9FTIv8B9myn1MWaC_2lJ-sMoeCDkusCsk4BYHjjCq04N0Y3CCJAaDdWRwgiQG,enr:-J24QDXyyxvQYsd0yfsN0cRr1lZ1N11zGTplMNlW4xNEc7LkPXh0NAJ9iSOVdRO95GPYAIc6xmyoCCG6_0JxdL3a0zaGAYiOoAjFgmlkgnY0gmlwhAPckbGHb3BzdGFja4OFQgCJc2VjcDI1NmsxoQJwoS7tzwxqXSyFL7g0JM-KWVbgvjfB8JA__T7yY_cYboN0Y3CCJAaDdWRwgiQG,enr:-J24QHmGyBwUZXIcsGYMaUqGGSl4CFdx9Tozu-vQCn5bHIQbR7On7dZbU61vYvfrJr30t0iahSqhc64J46MnUO2JvQaGAYiOoCKKgmlkgnY0gmlwhAPnCzSHb3BzdGFja4OFQgCJc2VjcDI1NmsxoQINc4fSijfbNIiGhcgvwjsjxVFJHUstK9L1T8OTKUjgloN0Y3CCJAaDdWRwgiQG,enr:-J24QG3ypT4xSu0gjb5PABCmVxZqBjVw9ca7pvsI8jl4KATYAnxBmfkaIuEqy9sKvDHKuNCsy57WwK9wTt2aQgcaDDyGAYiOoGAXgmlkgnY0gmlwhDbGmZaHb3BzdGFja4OFQgCJc2VjcDI1NmsxoQIeAK_--tcLEiu7HvoUlbV52MspE0uCocsx1f_rYvRenIN0Y3CCJAaDdWRwgiQG
  # -- Path to rollup config. Defaults to mainnet value.
  rollupConfig: mainnet/rollup.json

  resources: {}

  securityContext: {}

  service:
    type: ClusterIP
    ports:
      rpc:
        port: 9545
        protocol: TCP
      # p2p:
      #   port: 9222
      #   protocol: TCP
      # p2pudp:
      #   port: 9222
      #   protocol: UDP
      metrics:
        port: 7300
        protocol: TCP
      pprof:
        port: 6060
        protocol: TCP

  # @default -- See `values.yaml`
  livenessProbe:
    tcpSocket:
      port: rpc
    initialDelaySeconds: 60
    periodSeconds: 120

  # @default -- See `values.yaml`
  readinessProbe:
    tcpSocket:
      port: rpc
    initialDelaySeconds: 10
    periodSeconds: 10

image:
  repository: ghcr.io/base-org/node
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}

ingress:
  enabled: false
  className: ""
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

persistence:
  # -- Uses an EmptyDir when not enabled
  enabled: false
  # -- Use an existing PVC when persistence.enabled
  existingClaim: null
  # -- Access mode for the volume claim template
  accessModes:
    - ReadWriteOnce
  # -- Requested size for volume claim template
  size: 1600Gi
  # -- Use a specific storage class
  # E.g 'local-path' for local storage to achieve best performance
  # Read more (https://github.com/rancher/local-path-provisioner)
  storageClassName: null
  # -- Annotations for volume claim template
  annotations: {}
  # -- Selector for volume claim template
  selector: {}
  #   matchLabels:
  #     app.kubernetes.io/name: something

serviceMonitor:
  # -- If true, a ServiceMonitor CRD is created for a prometheus operator
  # https://github.com/coreos/prometheus-operator
  enabled: false
  # -- Path to scrape
  path: /debug/metrics
  # -- Alternative namespace for ServiceMonitor
  namespace: null
  # -- Additional ServiceMonitor labels
  labels: {}
  # -- Additional ServiceMonitor annotations
  annotations: {}
  # -- ServiceMonitor scrape interval
  interval: 1m
  # -- ServiceMonitor scheme
  scheme: http
  # -- ServiceMonitor TLS configuration
  tlsConfig: {}
  # -- ServiceMonitor scrape timeout
  scrapeTimeout: 30s
  # -- ServiceMonitor relabelings
  relabelings: []

nodeSelector: {}

tolerations: []
affinity: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
