
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spire.fullname" . }}
  labels:
    {{- include "spire.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "spire.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "spire.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "spire.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            {{- if .Values.args }}
            {{- toYaml .Values.args | nindent 12 }}
            {{- else if not .Values.args }}
            {{- if .Values.bootstrap }}
            - "bootstrap"
            {{- else  if .Values.stream }}
            - "stream"
            {{- else  if .Values.watch }}
            - "watch"
            {{- else  if .Values.kafka.enabled }}
            - "kafka"
            {{- range $arg := .Values.kafka.kafkaTopics }}
            - "{{ $arg }}"
            {{- end }}
            {{- else }}
            - "agent"
            {{- end }}
            {{- if .Values.logLevel }}
            - "-v"
            - "{{ .Values.logLevel | default "debug" }}"
            {{- end }}
            {{- if .Values.logFormat }}
            - "--log.format"
            - "{{ .Values.logFormat | default "text" }}"
            {{- end }}
            {{- if .Values.configHcl }}
            - "-c"
            {{- end }}
            {{- if .Values.configHcl }}
            - "/config/spire.hcl"
            {{- end }}
            {{- range $arg := .Values.customArgs }}
            - "{{ $arg }}"
            {{- end }}
            {{- end }}
          ports:
          {{- range $key, $val := .Values.service.ports }}
            - name: {{ $key }}
              containerPort: {{ $val.port }}
              protocol: {{ $val.protocol }}
          {{- end }}
          {{- if .Values.liveness.enabled }}
          livenessProbe:
            {{- toYaml .Values.liveness.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.readiness.enabled }}
          readinessProbe:
            {{- toYaml .Values.readiness.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          {{- if .Values.kafka.enabled }}
            - name: CFG_KAFKA_BROKERS
              value: "{{ .Values.kafka.kafkaEnpoint }}"
          {{- end }}
          {{- include "helpers.list-env-variables" . | indent 12 }}
          volumeMounts:
          {{- if .Values.configHcl }}
          - name: config
            mountPath: /config/spire.hcl
            subPath: spire.hcl
          {{- end }}
      volumes:
      {{- if .Values.configHcl }}
      - name: config
        configMap:
          name: {{ include "spire.fullname" . }}-config
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
