
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spire.fullname" . }}
  labels:
    {{- include "spire.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "spire.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- if .Values.keystore.enabled }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/config: {{ include (print $.Template.BasePath "/keystore-configmap.yaml") . | sha256sum }}
      {{- end }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "spire.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "spire.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.configHcl }}
          args: [ "-c", "/config/spire.hcl", "agent", "-v", "{{ .Values.logLevel | default "debug" }}, "--log.format", "{{ .Values.logFormat | default "text" }}"]
          {{- else }}
          args: ["agent", "-v", "{{ .Values.logLevel | default "debug" }}", "--log.format", "{{ .Values.logFormat | default "text" }}"]
          {{- end }}
          ports:
          {{- range $key, $val := .Values.service.ports }}
            - name: {{ $key }}
              containerPort: {{ $val.port }}
              protocol: {{ $val.protocol }}
          {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          {{- include "helpers.list-env-variables" . | indent 12 }}
          volumeMounts:
          {{- if .Values.configHcl }}
          - name: config
            mountPath: /config/spire.hcl
            subPath: spire.hcl
          {{- end }}
          {{- if .Values.keystore.enabled }}
          - name: keystore
            mountPath: /keystore/
          - name: password
            mountPath: /password/
          {{- end }}
      volumes:
      {{- if .Values.configHcl }}
      - name: config
        configMap:
          name: {{ include "spire.fullname" . }}-config
      {{- end }}
      {{- if .Values.keystore.enabled }}
      {{- if .Values.keystore.existingSecret }}
      - name: keystore
        secret:
          secretName: {{ .Values.keystore.existingSecret }}
          items:
          - key: keystoreFile
            path: keystore.json
      - name: password
        secret:
          secretName: {{ .Values.keystore.existingSecret }}
          items:
          - key: password
            path: password.txt
      {{- else }}
      - name: keystore
        configMap:
          name: {{ include "spire.fullname" . }}-keystore
          items:
          - key: keystore.json
            path: keystore.json
      - name: password
        configMap:
          name: {{ include "spire.fullname" . }}-keystore
          items:
          - key: password.txt
            path: password.txt
      {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
