apiVersion: v1
kind: Service
metadata:
  name: {{ include "spire.fullname" . }}
  annotations:
  {{- with .Values.service.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "spire.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.loadBalancerClass }}
  loadBalancerClass: {{ . | quote }}
  {{- end }}
  {{- with .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . | quote }}
  {{- end }}
  {{- with .Values.service.trafficDistribution }}
  trafficDistribution: {{ . | quote }}
  {{- end }}
  ports:
    {{- range $key, $val := .Values.service.ports }}
    - port: {{ $val.port }}
      targetPort: {{ $val.port }}
      protocol: {{ $val.protocol }}
      name: {{ $key }}
    {{- end }}
  selector:
    {{- include "spire.selectorLabels" . | nindent 4 }}
