apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tor-proxy.fullname" . }}
  labels:
    {{- include "tor-proxy.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "tor-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tor-proxy.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tor-proxy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.torConfig }}
      initContainers:
      - name: copy-tor-keys
        image: busybox
        command: ['sh', '-c', 'cp /keys/* /var/lib/tor/hidden_services/']
        volumeMounts:
        - name: tor-hidden-services
          mountPath: /var/lib/tor/hidden_services
        - name: tor-keys
          mountPath: /keys
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          # livenessProbe:
          #   exec:
          #     command:
          #     - /bin/sh
          #     - -c
          #     - "echo authenticate '""' | nc 127.0.0.1 {{ .Values.service.port }} && echo signal NEWNYM | nc 127.0.0.1 {{ .Values.service.port }}"
          #   initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          #   periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          # readinessProbe:
          #   exec:
          #     command:
          #     - /bin/sh
          #     - -c
          #     - "echo authenticate '""' | nc 127.0.0.1 {{ .Values.service.port }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          {{- include "helpers.list-env-variables" . | indent 12 }}
          volumeMounts:
            - name: tor-hidden-services
              mountPath: /var/lib/tor/hidden_services
      volumes:
        {{- if .Values.torConfig }}
        - name: tor-keys
          secret:
          {{- if .Values.torConfig.existingSecret }}
            secretName: {{ .Values.torConfig.existingSecret}}
          {{- else }}
            secretName: {{ include "tor-proxy.fullname" . }}-key
            items:
            - key: hs_ed25519_secret_key
              path: hs_ed25519_secret_key
            - key: hs_ed25519_public_key
              path: hs_ed25519_public_key
            - key: hostname
              path: hostname
          {{- end }}
        {{- end }}
        - name: tor-hidden-services
          emptyDir: {}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
