{{- if .Values.torConfig.torKeys }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tor-proxy.fullname" . }}-key
type: Opaque
data:
  hs_ed25519_secret_key: {{ .Values.torConfig.torKeys.secret_key }}
  hs_ed25519_public_key: {{ .Values.torConfig.torKeys.public_key }}
  hostname: {{ .Values.torConfig.torKeys.hostname | b64enc | quote }}
{{- end }}
