spectre:
  enabled: true
  image:
    tag: "sha-5e277a6"
  fullnameOverride: "spectre"
  ethConfig: {}
    # ethFrom:
    #   existingSecret: "eth-keys"
    #   key: "ethFrom"
    # ethKeys:
    #   existingSecret: "eth-keys"
    #   key: "ethKeyStore"
    # ethPass:
    #   existingSecret: "eth-keys"
    #   key: "ethPass"
  env:
    # non sensitive variables
    # refer to https://github.com/chronicleprotocol/oracle-suite/tree/master/cmd/spectre#environment-variables
    normal: {}
      # CFG_ETH_FROM: ${ETH_FROM_D}
      # CFG_ETH_KEYS: ${ETH_KEYS_D}
      # CFG_ETH_PASS: ""
      # CFG_FEEDS: "${ETH_FROM_A},${ETH_FROM_B},${ETH_FROM_C}"
      # CFG_LIBP2P_BOOTSTRAP_ADDRS: "/dns4/bootstrap.local/tcp/8000/p2p/12D3KooWJgSBDkfdkoXNBBS91uaM1FRE4GowChEgr4SWDKEz75Rq"
      # CFG_GOFER_OPENEXCHANGERATES_API_KEY:
      # CFG_WEBAPI_ENABLE: 0
      # CFG_ETH_RPC_URLS: "${ETH_RPCS}" # comma separated list of ethereum rpc urls
      # CFG_ETH_CHAIN_ID: ${ETH_CHID} # ethereum chain id
      # CFG_ARB_RPC_URLS: ${ARB_RPCS} # comma separated list of arbitrum rpc urls
      # CFG_ARB_CHAIN_ID: ${ARB_CHID} # arbitrum chain id
      # CFG_OPT_RPC_URLS: ${OPT_RPCS} # comma separated list of optimism rpc urls
      # CFG_OPT_CHAIN_ID: ${OPT_CHID} # optimism chain id

tor-proxy:
  enabled: true
  fullnameOverride: "tor-proxy"
  env:
    # non sensitive variables
    # refer to https://github.com/chronicleprotocol/oracle-suite/tree/master/cmd/spire#environment-variables
    normal:
      TOR_EXTRA_ARGS: |
        AutomapHostsOnResolve 1
        ControlSocketsGroupWritable 1
        CookieAuthentication 1
        CookieAuthFileGroupReadable 1
        DNSPort 5353
        ExitPolicy reject *:*
        Log notice stderr
        RunAsDaemon 0
        ControlSocket /home/tor/.tor/control_socket
        CookieAuthFile /home/tor/.tor/control_socket.authcookie
        DataDirectory /home/tor/.tor
        HiddenServiceDir /var/lib/tor/hidden_services
        HiddenServicePort 8888 spectre:8080
        HiddenServiceVersion 3
  torConfig: {}
    # existingSecret: ""
    ## OR specify a private key
    # torKeys:
    #   secret_key: "PT0g......."
    #   public_key: "PT....=="
    #   hostname: "some.onion"
# -- Extra K8s manifests to deploy
extraObjects: []
  # - apiVersion: "kubernetes-client.io/v1"
  #   kind: ExternalSecret
  #   metadata:
  #     name: some-secret
  #   spec:
  #     backendType: someBackend
  #     data:
  #       - key: somekey
  #         name: somename
