ghost:
  # values for ghost: https://github.com/chronicleprotocol/charts/blob/main/charts/ghost/values.yaml
  enabled: true
  image:
    tag: "0.15.0"
  fullnameOverride: "ghost"
  ethConfig: {}
    # ethFrom:
    #   existingSecret: ""
    #   key: "ethFrom"
    # ethKeys:
    #   existingSecret: ""
    #   key: "ethKeyStore"
    # ethPass:
    #   existingSecret: ""
    #   key: "ethPass"

  service:
    type: ClusterIP
    ports:
      libp2p:
        port: 8000
        protocol: TCP

  logLevel: null
  logFormat: null

  ethRpcUrl: null
  ethChainId: null
  rpcUrl: null
  chainId: null

  env:
    normal:
      # if no .Values.ethConfig.eth*.existingSecret is specified, then the following env vars need to be supplied:
      # CFG_ETH_FROM: ""
      # CFG_ETH_PASS: ""
      # CFG_ETH_KEYS: ''

      # CFG_ENVIRONMENT: "prod"
      # CFG_FEEDS: "prod"

      CFG_WEBAPI_ENABLE: 1
      CFG_WEBAPI_LISTEN_ADDR: ""
      CFG_WEBAPI_SOCKS5_PROXY_ADDR: "tor-proxy:9050"

musig:
  # values for musig: https://github.com/chronicleprotocol/charts/blob/main/charts/musig/values.yaml
  enabled: true
  fullnameOverride: "musig"
  image:
    tag: "0.4.0"
  imagePullSecrets: []
  service:
    type: ClusterIP
    ports:
      libp2p:
        port: 8001
        protocol: TCP
      webapi:
        port: 8080
        protocol: TCP

  logLevel: null
  logFormat: null

  ethChainId: 1
  ethRpcUrl: null

  ethConfig: {}
    # ethFrom:
    #   existingSecret: ""
    #   key: "ethFrom"
    # ethKeys:
    #   existingSecret: ""
    #   key: "ethKeyStore"
    # ethPass:
    #   existingSecret: ""
    #   key: "ethPass"
  env:
    normal:
      # if no .Values.ethConfig.eth*.existingSecret is specified, then the following env vars need to be supplied:
      # CFG_ETH_FROM: ""
      # CFG_ETH_PASS: ""
      # CFG_ETH_KEYS: ''

      # CFG_ENVIRONMENT: "prod"
      # CFG_FEEDS: "prod"

      CFG_WEBAPI_ENABLE: 1
      CFG_WEBAPI_LISTEN_ADDR: ":8080"
      CFG_WEBAPI_SOCKS5_PROXY_ADDR: "tor-proxy:9050"

tor-proxy:
  enabled: true
  fullnameOverride: "tor-proxy"
  service:
    type: ClusterIP
    ports:
      socks:
        port: 9050
        protocol: TCP
      # musig:
      #   port: 8888
      #   protocol: TCP
  env:
    # non sensitive variables
    # refer to https://github.com/chronicleprotocol/oracle-suite/tree/master/cmd/spire#environment-variables
    normal:
      TOR_EXTRA_ARGS: |
        SocksPort 0.0.0.0:9050
        HiddenServiceDir /var/lib/tor/hidden_services
        HiddenServicePort 8888 musig:8080
  torConfig: {}
    # existingSecret: ""
    # OR specify a private key
    # torKeys: {}
      # secret_key: null
      # public_key: null
      # hostname: null

# -- Extra K8s manifests to deploy
extraObjects: []
  # - apiVersion: "kubernetes-client.io/v1"
  #   kind: ExternalSecret
  #   metadata:
  #     name: some-secret
  #   spec:
  #     backendType: someBackend
  #     data:
  #       - key: somekey
  #         name: somename
