# -- Ghost component of the feed
ghost:
  # -- values for musig: refer to the [ghost](https://github.com/chronicleprotocol/charts/blob/main/charts/ghost/values.yaml) subchart
  enabled: true
  image:
    tag: "0.29.1"
  fullnameOverride: "ghost"

  # -- Provide eth keystore, eth from address and eth password from existing secrets
  ethConfig: {}
    # ethFrom:
    #   existingSecret: ""
    #   key: "ethFrom"
    # ethKeys:
    #   existingSecret: ""
    #   key: "ethKeyStore"
    # ethPass:
    #   existingSecret: ""
    #   key: "ethPass"

  service:
    type: LoadBalancer
    ports:
      libp2p:
        port: 8000
        protocol: TCP
  # -- log level (debug, info, warning, error)
  logLevel: warning
  # -- log format (json, text)
  logFormat: null
  # -- WATCHDOG onchain registry address
  watchdogConfigReg: "0x94Fea534aef6df5cF66C2DAE5CE0A05d10C068F3"
  # -- WATCHDOG interval (in seconds)
  watchdogInterval: "900s"
  # -- eth RPC url (always ethereum mainnet)
  ethRpcUrl: null
  # -- eth chain id for `ethRpcUrl`
  ethChainId: 1

  # -- default eth RPC url (can be testnet or mainnet)
  rpcUrl: null
  # -- default eth chain id for `rpcUrl`
  chainId: null

  # -- non-sensitive variables passed to container as environment variables
  env:
    normal:
      # if no .Values.ethConfig.eth*.existingSecret is specified, then the following env vars need to be supplied:
      # CFG_ETH_FROM: ""
      # CFG_ETH_PASS: ""
      # CFG_ETH_KEYS: ''

      WATCHDOG_ETH_FROM: "0x00000000000000000000000000000000000000000000000"

      CFG_WEBAPI_ENABLE: 1
      CFG_WEBAPI_LISTEN_ADDR: ""
      CFG_WEBAPI_SOCKS5_PROXY_ADDR: "tor-proxy:9050"

# -- Musig component of the feed
musig:
  # -- values for musig: refer to the [musig](https://github.com/chronicleprotocol/charts/blob/main/charts/musig/values.yaml) subchart
  enabled: true
  fullnameOverride: "musig"
  image:
    tag: "0.29.1"
  imagePullSecrets: []

  service:
    type: LoadBalancer
    ports:
      libp2p:
        port: 8001
        protocol: TCP
      webapi:
        port: 8080
        protocol: TCP

  # -- log level (debug, info, warning, error)
  logLevel: warning

  # -- log format (json, text)
  logFormat: null

  # -- WATCHDOG onchain registry address
  watchdogConfigReg: "0x94Fea534aef6df5cF66C2DAE5CE0A05d10C068F3"
  # -- WATCHDOG interval (in seconds)
  watchdogInterval: "900s"

  # -- default eth RPC url (can be testnet or mainnet). Must mach same chain `.Values.ghost.rpcUrl`
  ethRpcUrl: null

  # -- default eth chain id for `ethRpcUrl`
  ethChainId: 1

  # -- Provide eth keystore, eth from address and eth password from existing secrets
  ethConfig: {}
    # ethFrom:
    #   existingSecret: ""
    #   key: "ethFrom"
    # ethKeys:
    #   existingSecret: ""
    #   key: "ethKeyStore"
    # ethPass:
    #   existingSecret: ""
    #   key: "ethPass"

  # -- non-sensitive variables passed to container as environment variables
  env:
    normal:
      # if no .Values.ethConfig.eth*.existingSecret is specified, then the following env vars need to be supplied:
      # CFG_ETH_FROM: ""
      # CFG_ETH_PASS: ""
      # CFG_ETH_KEYS: ''

      WATCHDOG_ETH_FROM: "0x00000000000000000000000000000000000000000000000"

      CFG_WEBAPI_ENABLE: 1
      CFG_WEBAPI_LISTEN_ADDR: ":8080"
      CFG_WEBAPI_SOCKS5_PROXY_ADDR: "tor-proxy:9050"

# -- Tor proxy component of the feed for WEB_API transport.
tor-proxy:
  # -- values for tor-proxy: refer to the [tor-proxy](https://github.com/chronicleprotocol/charts/blob/main/charts/tor-proxy/values.yaml) subchart
  enabled: true
  fullnameOverride: "tor-proxy"
  service:
    type: ClusterIP
    ports:
      socks:
        port: 9050
        protocol: TCP
      # musig:
      #   port: 8888
      #   protocol: TCP

  # -- non-sensitive variables passed to container as environment variables
  env:
    normal:
      TOR_EXTRA_ARGS: |
        SocksPort 0.0.0.0:9050
        HiddenServiceDir /var/lib/tor/hidden_services
        HiddenServicePort 8888 musig:8080

  # -- provide tor keys from existing secret
  torConfig: {}
    # existingSecret: ""
    # OR specify a private key
    # torKeys: {}
      # secret_key: null
      # public_key: null
      # hostname: null

# -- Extra K8s manifests to deploy
extraObjects: []
  # - apiVersion: "kubernetes-client.io/v1"
  #   kind: ExternalSecret
  #   metadata:
  #     name: some-secret
  #   spec:
  #     backendType: someBackend
  #     data:
  #       - key: somekey
  #         name: somename
