spire:
  enabled: true
  bootstrap: true
  service:
    type: ClusterIP
    ports:
      libp2p:
        port: 8000
        protocol: TCP
  env:
    normal:
      CFG_LIBP2P_BOOTSTRAP_ADDRS: ""
      CFG_LIBP2P_PK_SEED: ""

ghost:
  enabled: true
  ethConfig: {}
    # ethFrom:
    #   existingSecret: "eth-keys"
    #   key: "ethFrom"
    # ethKeys:
    #   existingSecret: "eth-keys"
    #   key: "ethKeyStore"
    # ethPass:
    #   existingSecret: "eth-keys"
    #   key: "ethPass"
  env: {}
    # non sensitive variables
    # refer to https://github.com/chronicleprotocol/oracle-suite/tree/master/cmd/spire#environment-variables
    # normal:
    #   CFG_FEEDS: ""
    #   CFG_LIBP2P_BOOTSTRAP_ADDRS: "/dns4/<bootstrap-hostname>/tcp/8000/p2p/<libp2p-pub-key>"
    #   CFG_GOFER_OPENEXCHANGERATES_API_KEY:
    #   CFG_WEBAPI_ENABLE: 0
    #   # Provide ETH keys as env vars
    #   CFG_ETH_FROM: ""
    #   CFG_ETH_PASS: ""
    #   CFG_ETH_KEYS: ''

musig:
  enabled: true
  ethConfig: {}
    # ethFrom:
    #   existingSecret: "eth-keys"
    #   key: "ethFrom"
    # ethKeys:
    #   existingSecret: "eth-keys"
    #   key: "ethKeyStore"
    # ethPass:
    #   existingSecret: "eth-keys"
    #   key: "ethPass"
  env: {}
    # non sensitive variables
    # refer to https://github.com/chronicleprotocol/oracle-suite/tree/master/cmd/musig#environment-variables
    # normal:
    #   CFG_ETH_FROM: ""
    #   CFG_ETH_KEYS: ''
    #   CFG_ETH_PASS: ""
    #   CFG_FEEDS: ""
    #   CFG_LIBP2P_BOOTSTRAP_ADDRS: "/dns4/<bootstrap-hostname>/tcp/8000/p2p/<libp2p-pub-key>"
    #   CFG_GOFER_OPENEXCHANGERATES_API_KEY:
    #   CFG_WEBAPI_ENABLE: 0
    #   CFG_MUSIG_SIGNERS_COUNT: 3

# -- Extra K8s manifests to deploy
extraObjects: []
  # - apiVersion: "kubernetes-client.io/v1"
  #   kind: ExternalSecret
  #   metadata:
  #     name: some-secret
  #   spec:
  #     backendType: someBackend
  #     data:
  #       - key: somekey
  #         name: somename
