ghost:
  enabled: true
  fullnameOverride: "ghost"
  ethConfig: {}
    # ethFrom:
    #   existingSecret: "eth-keys"
    #   key: "ethFrom"
    # ethKeys:
    #   existingSecret: "eth-keys"
    #   key: "ethKeyStore"
    # ethPass:
    #   existingSecret: "eth-keys"
    #   key: "ethPass"
  env:
    # non sensitive variables
    # refer to https://github.com/chronicleprotocol/oracle-suite/tree/master/cmd/spire#environment-variables
    normal:
      CFG_WEBAPI_SOCKS5_PROXY_ADDR: tor-proxy:9050
      CFG_WEBAPI_ENABLE: 1
    #   CFG_FEEDS: ""
    #   CFG_LIBP2P_BOOTSTRAP_ADDRS: "/dns4/spire-bootstrap.default.svc.local/tcp/8000/p2p/12D3KooWJgSBDkfdkoXNBBS91uaM1FRE4GowChEgr4SWDKEz75Rq"
    #   CFG_GOFER_OPENEXCHANGERATES_API_KEY:
    #   # Provide ETH keys as env vars
    #   CFG_ETH_FROM: ""
    #   CFG_ETH_PASS: ""
    #   CFG_ETH_KEYS: ''
musig:
  enabled: true
  fullnameOverride: "musig"
  service:
    type: ClusterIP
    port: 8080
  ethConfig: {}
    # ethFrom:
    #   existingSecret: "eth-keys"
    #   key: "ethFrom"
    # ethKeys:
    #   existingSecret: "eth-keys"
    #   key: "ethKeyStore"
    # ethPass:
    #   existingSecret: "eth-keys"
    #   key: "ethPass"
  env:
    # non sensitive variables
    # refer to https://github.com/chronicleprotocol/oracle-suite/tree/master/cmd/musig#environment-variables
    normal:
    #  CFG_ETH_FROM: ""
    #  CFG_ETH_PASS: ""
    #  CFG_ETH_KEYS: ''
    #  CFG_FEEDS: ""
    #  CFG_LIBP2P_BOOTSTRAP_ADDRS: "/dns4/spire-bootstrap.default.svc.local/tcp/8000/p2p/<>"
    #  CFG_GOFER_OPENEXCHANGERATES_API_KEY:
    #  CFG_MUSIG_SIGNERS_COUNT: 3
      CFG_WEBAPI_ENABLE: 1
      CFG_WEBAPI_SOCKS5_PROXY_ADDR: tor-proxy:9050

tor-proxy:
  enabled: true
  fullnameOverride: "tor-proxy"
  env:
    # non sensitive variables
    # refer to https://github.com/chronicleprotocol/oracle-suite/tree/master/cmd/spire#environment-variables
    normal:
      TOR_EXTRA_ARGS: |
        AutomapHostsOnResolve 1
        ControlSocketsGroupWritable 1
        CookieAuthentication 1
        SOCKSPort 0.0.0.0:9050
        CookieAuthFileGroupReadable 1
        DNSPort 5353
        ExitPolicy reject *:*
        Log notice stderr
        RunAsDaemon 0
        ControlSocket /home/tor/.tor/control_socket
        CookieAuthFile /home/tor/.tor/control_socket.authcookie
        DataDirectory /home/tor/.tor
        HiddenServiceDir /var/lib/tor/hidden_services
        HiddenServicePort 8888 musig:8080
        HiddenServiceVersion 3
  torConfig: {}
    # existingSecret: ""
    ## OR specify a private key
    # torKeys:
    #   secret_key: "PT0g......."
    #   public_key: "PT....=="
    #   hostname: "some.onion"
# -- Extra K8s manifests to deploy
extraObjects: []
  # - apiVersion: "kubernetes-client.io/v1"
  #   kind: ExternalSecret
  #   metadata:
  #     name: some-secret
  #   spec:
  #     backendType: someBackend
  #     data:
  #       - key: somekey
  #         name: somename
