ghost:
  logLevel: debug
  logFormat: text
  # values for ghost: https://github.com/chronicleprotocol/charts/blob/main/charts/ghost/values.yaml
  ethRpcUrl: 'https://rpc.somedomain/eth'
  ethChainId: 1
  rpcUrl: 'https://rpc.somedomain/eth'
  chainId: 1

  watchdogConfigReg: "0x94Fea534aef6df5cF66C2DAE5CE0A05d10C068F3"
  watchdogInterval: "5s"

  # --Environment variable listing
  env:
    normal:
      GOLOG_LOG_LEVEL: pubsub=debug
      # if no .Values.ethConfig.eth*.existingSecret is specified, then the following env vars need to be supplied:
      # These are dummy values. please do not use these eth keys at all as you will lose any funds
      CFG_ETH_FROM: "0x1e68967a10a30602EbBa297cffeCC3645cB28D99"
      CFG_ETH_PASS: ""
      CFG_ETH_KEYS: '{"crypto":{"cipher":"aes-128-ctr","cipherparams":{"iv":"22ae1be4ab7cd766e05c03e334deb9d2"},"ciphertext":"56439cc948fbecff1c252f5cede620f65821c6446ddb6d4bfa38f17754555a44","kdf":"scrypt","kdfparams":{"dklen":32,"n":8192,"p":1,"r":8,"salt":"7dcaf2f0196aa5c9d05dc15fac39ec15dbd99db2311813fd3d1d98324faf05c5"},"mac":"191ffca516d2c263402bd03e4cf1a6df60ebc833f489346fefdf0fe89138f305"},"id":"aea697d6-94d9-4433-bd69-4808597b0768","version":3}'

      WATCHDOG_ETH_FROM: "0x00000000000000000000000000000000000000000000000"

      CFG_ETH_RPC_URLS: 'https://rpc.somedomain/eth'
      CFG_ETH_CHAIN_ID: '1'
      CFG_CHAIN_RPC_URLS: 'https://rpc.somedomain/eth'
      CFG_CHAIN_ID: '1'
      WATCHDOG_CONFIG_REGISTRY: '0x94Fea534aef6df5cF66C2DAE5CE0A05d10C068F3'
      WATCHDOG_INTERVAL: 900s
      CFG_ARB_CHAIN_RPC_URLS: 'https://rpc.somedomain/arb1'
      CFG_CHAIN_NAME: eth
      CFG_ETH_ARCH_RPC_URLS: 'https://mainnet.infura.io/v3/'
      CFG_ETH_CHAIN_RPC_URLS: 'https://rpc.somedomain/eth'
      CFG_GNO_CHAIN_RPC_URLS: 'https://rpc.somedomain/gno'
      CFG_LIBP2P_EXTERNAL_ADDR: /dns/ghost-feed.somedomain
      CFG_LIBP2P_SUBSCRIPTION_BUFFER_SIZE: '4096'
      CFG_LIBP2P_VALIDATE_QUEUE_SIZE: '4096'
      CFG_MNT_CHAIN_RPC_URLS: 'https://rpc.somedomain/mantle'
      CFG_OPT_CHAIN_RPC_URLS: 'https://rpc.somedomain/oeth'
      CFG_POL_CHAIN_RPC_URLS: 'https://rpc.somedomain/zkevm'
      CFG_WEBAPI_ENABLE: '1'
      CFG_WEBAPI_LISTEN_ADDR: ':8080'
      CFG_WEBAPI_SOCKS5_PROXY_ADDR: 'tor-proxy:9050'
      CFG_WEB_URL: '44bd7fi6kfrsk2sbqp7qch7wdze4muyrzspdywam4aumz3ioft5pnoad.onion'

tor-proxy:
  torConfig:
    torKeys:
      secret_key: "PT0gZWQyNTUxOXYxLXNlY3JldDogdHlwZTAgPT0AAAB48ZoWgg85pG5F3GVsoh1SxulTfa4nR8GVWlzNiFTQRk7LTqzUAmXo7pvB66NaboaZ+p1DqMqJqfv15HJZ4lut"
      public_key: "PT0gZWQyNTUxOXYxLXB1YmxpYzogdHlwZTAgPT0AAADnAj+VHlFjJWpBg/8BH/YeScZTEcyePFgM4CjM7Q4s+g=="
      hostname: "44bd7fi6kfrsk2sbqp7qch7wdze4muyrzspdywam4aumz3ioft5pnoad.onion"
