global:
  logLevel: debug
  logFormat: text
  # values for ghost: https://github.com/chronicleprotocol/charts/blob/main/charts/validator/values.yaml
  liveness:
    enabled: false
  readiness:
    enabled: false

ghost:
  watchdogInterval: "5s"
  rpcUrl: https://eth.llamarpc.com
  service:
    # -- Type of service for the validator, can also be `LoadBalancer`
    type: ClusterIP

  env:
    normal:
      # GOLOG_LOG_LEVEL: pubsub=debug
      # if no .Values.ethConfig.eth*.existingSecret is specified, then the following env vars need to be supplied:
      # These are dummy values. please do not use these eth keys at all as you will lose any funds
      CFG_ETH_FROM: "0x535e1946bD6F571e9E7f53433b3756478586384d"
      CFG_ETH_PASS: "test888"
      CFG_ETH_KEYS: '{"address":"535e1946bd6f571e9e7f53433b3756478586384d","crypto":{"cipher":"aes-128-ctr","ciphertext":"b782b4988c2ec5904f2adf9b3db0984d0032cfe34e1740e093d724e844fbc453","cipherparams":{"iv":"a34d149bb369fbec1e295352cf733829"},"kdf":"scrypt","kdfparams":{"dklen":32,"n":262144,"p":1,"r":8,"salt":"094aa5e2499767c050a6c817a124d642259b235b52f6d8cb374461ef02b9d2e9"},"mac":"5405b9d0878959fa28d9751b5a0d3ee41c875807c66df69f14d63ee231d43cb7"},"id":"4ca6d42e-5e38-466e-934d-8f0ac799d99c","version":3}'

      WATCHDOG_ETH_FROM: "0x0000000000000000000000000000000000000000"

vao:
  watchdogInterval: "5s"
  service:
    # -- Type of service for the validator, can also be `LoadBalancer`
    type: ClusterIP

  env:
    normal:
      # GOLOG_LOG_LEVEL: pubsub=debug
      # if no .Values.ethConfig.eth*.existingSecret is specified, then the following env vars need to be supplied:
      # These are dummy values. please do not use these eth keys at all as you will lose any funds

      CFG_ETH_FROM: "0x535e1946bD6F571e9E7f53433b3756478586384d"
      CFG_ETH_PASS: "test888"
      CFG_ETH_KEYS: '{"address":"535e1946bd6f571e9e7f53433b3756478586384d","crypto":{"cipher":"aes-128-ctr","ciphertext":"b782b4988c2ec5904f2adf9b3db0984d0032cfe34e1740e093d724e844fbc453","cipherparams":{"iv":"a34d149bb369fbec1e295352cf733829"},"kdf":"scrypt","kdfparams":{"dklen":32,"n":262144,"p":1,"r":8,"salt":"094aa5e2499767c050a6c817a124d642259b235b52f6d8cb374461ef02b9d2e9"},"mac":"5405b9d0878959fa28d9751b5a0d3ee41c875807c66df69f14d63ee231d43cb7"},"id":"4ca6d42e-5e38-466e-934d-8f0ac799d99c","version":3}'

      WATCHDOG_ETH_FROM: "0x15F1eF3e0460B2aaa0033a37380Abbe63BE4f48C"
