{{- if index .Values "tor-proxy" "enabled" }}
apiVersion: tor.k8s.torproject.org/v1alpha2
kind: OnionService
metadata:
  name: {{ include "spectre.fullname" . }}
  labels:
    {{- include "spectre.labels" . | nindent 4 }}
spec:
  version: 3
  rules:
    - port:
        number: 8888
      backend:
        service:
          name: {{ include "spectre.fullname" . }}
          port:
            number: {{ .Values.service.ports.listen.port }}
{{- end }}
