apiVersion: v1
kind: Service
metadata:
  name: {{ include "spectre.fullname" . }}-metrics
  annotations:
  {{- with .Values.service.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "spectre.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    {{- include "spectre.selectorLabels" . | nindent 4 }}
