apiVersion: v1
kind: Service
metadata:
  name: {{ include "base.fullname" . }}
  annotations:
  {{- with .Values.geth.service.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "base.labels" . | nindent 4 }}
spec:
  type: {{ .Values.geth.service.type }}
  ports:
    {{- range $key, $val := .Values.geth.service.ports }}
    - port: {{ $val.port }}
      targetPort: {{ $val.port }}
      protocol: {{ $val.protocol }}
      name: {{ $key }}
    {{- end }}
  selector:
    {{- include "base.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "base.fullname" . }}-op-node
  annotations:
  {{- with .Values.opNode.service.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "base.labels" . | nindent 4 }}
spec:
  type: {{ .Values.opNode.service.type }}
  ports:
    {{- range $key, $val := .Values.opNode.service.ports }}
    - port: {{ $val.port }}
      targetPort: {{ $val.port }}
      protocol: {{ $val.protocol }}
      name: {{ $key }}
    {{- end }}
  selector:
    {{- include "base.selectorLabels" . | nindent 4 }}
