apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "musig.fullname" . }}
  labels:
    {{- include "musig.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "musig.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "musig.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "musig.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          {{- if .Values.hostNetwork }}
          hostNetwork: true
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          args:
            - "run"
            - "-v"
            - "{{ .Values.logLevel | default "warning" }}"
            - "--log.format"
            - "{{ .Values.logFormat | default "text" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          {{- range $key, $val := .Values.service.ports }}
            - name: {{ $key }}
              containerPort: {{ $val.port }}
              protocol: {{ $val.protocol }}
          {{- end }}
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          env:
            - name: CFG_LIBP2P_LISTEN_ADDRS
              value: "/ip4/0.0.0.0/tcp/{{ .Values.service.ports.libp2p.port | default 8001 }}"
          {{- if eq .Values.service.type "LoadBalancer" }}
            - name: CFG_LIBP2P_EXTERNAL_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          {{- end }}
          {{- if .Values.ethChainId }}
            - name: CFG_ETH_CHAIN_ID
              value: "{{ int .Values.ethChainId }}"
          {{- end }}
          {{- if .Values.ethRpcUrl }}
            - name: CFG_RPC_URLS
              value: "[{{ .Values.ethRpcUrl }}]"
          {{- end }}
          {{- if .Values.watchogConfigReg }}
            - name: WATCHDOG_CONFIG_REGISTRY
              value: "{{ .Values.watchogConfigReg }}"
          {{- end }}
          {{- if .Values.watchogInterval }}
            - name: WATCHDOG_INTERVAL
              value: "{{ .Values.watchogInterval | default "900s" }}"
          {{- end }}
          {{- if .Values.ethConfig }}
            - name: CFG_ETH_FROM
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.ethConfig.ethFrom.existingSecret }}
                  key: {{ .Values.ethConfig.ethFrom.key }}
            - name: CFG_ETH_KEYS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.ethConfig.ethKeys.existingSecret }}
                  key: {{ .Values.ethConfig.ethKeys.key }}
            - name: CFG_ETH_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.ethConfig.ethPass.existingSecret }}
                  key: {{ .Values.ethConfig.ethPass.key }}
          {{- end }}

          {{- include "helpers.list-env-variables" . | indent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
