{{- $count := .Values.feedInstances | int }}
{{- range $i := until $count }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: musig-{{ $i }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: musig-{{ $i }}
  template:
    metadata:
      labels:
        app: musig-{{ $i }}
    spec:
      containers:
        - name: musig
          image: "ghcr.io/chronicleprotocol/musig"
          env:
            - name: INSTANCE_ID
              value: "musig-{{ $i }}"
          volumeMounts:
            - name: my-secret
              mountPath: /etc/secrets
              readOnly: true
      volumes:
        - name: my-secret
          emptyDir: {}
{{- end }}
