apiVersion: v1
kind: Service
metadata:
  name: {{ include "musig.fullname" . }}
  labels:
    {{- include "musig.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $key, $val := .Values.service.ports }}
    - port: {{ $val.port }}
      targetPort: {{ $val.port }}
      protocol: {{ $val.protocol }}
      name: {{ $key }}
    {{- end }}
  selector:
    {{- include "musig.selectorLabels" . | nindent 4 }}
