apiVersion: v1
kind: Service
metadata:
  name: {{ include "leeloo.fullname" . }}
  labels:
    {{- include "leeloo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: listener
      protocol: TCP
      name: listener
  selector:
    {{- include "leeloo.selectorLabels" . | nindent 4 }}
