apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    {{- include "hyperliquid.labels" . | nindent 4 }}
  name: '{{ include "hyperliquid.fullname" . }}-pruner'
spec:
  replicas: {{ .Values.pruner.replicas }}
  selector:
    matchLabels:
      {{- include "hyperliquid.selectorLabels" . | nindent 6 }}
  strategy: {}
  template:
    metadata:
      labels:
        {{- include "hyperliquid.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - image: '{{ tpl .Values.pruner.repository.image $ }}:{{ tpl .Values.pruner.repository.tag $ | default "latest" }}'
        imagePullPolicy: {{ .Values.pruner.imagePullPolicy }}
        name: pruner
        {{- if .Values.pruner.resources }}
        resources:
          {{ .Values.pruner.resources | toYaml | nindent 10 }}
        {{- end }}
        volumeMounts:
        {{- if .Values.pruner.persistence.hl_data.enabled }}
        - mountPath: /home/hluser/hl/data
          name: hl-data
        {{- end }}
      {{- if .Values.pullSecrets }}
      imagePullSecrets:
      {{- .Values.pullSecrets | toYaml | nindent 6 }}
      {{- end }}
      {{- if .Values.pruner.nodeSelector }}
      nodeSelector:
        {{- .Values.pruner.nodeSelector | toYaml | nindent 8 }}
      {{- end }}
      {{- if ne .Values.pruner.serviceAccount "" }}
      serviceAccountName: {{ .Values.pruner.serviceAccount | quote }}
      {{- end }}
      volumes:
      {{- if .Values.pruner.persistence.hl_data.enabled }}
      - name: hl-data
        persistentVolumeClaim:
          claimName: '{{ include "hyperliquid.fullname" . }}-pruner-hl-data'
      {{- end }}
