apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "omnia-feed.fullname" . }}-gofer
  labels:
    {{- include "omnia-feed.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      service: {{ include "omnia-feed.fullname" . }}-gofer
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        service: {{ include "omnia-feed.fullname" . }}-gofer
        {{- include "omnia-feed.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "omnia-feed.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.gofer.image.repository }}:{{ .Values.gofer.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          args: [ "-c", "/config/gofer.json", "agent" ]
          ports:
            - name: http
              containerPort: {{ .Values.gofer.service.port }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: config
            mountPath: /config/gofer.json
            subPath: gofer.json
          env:
          {{- include "helpers.list-env-variables" . | indent 12 }}
          {{- if not .Values.externalSecrets.enabled }}
          {{- include "helpers.secret-env-variables" . | indent 12 }}
          {{- end }}
          {{- if .Values.externalSecrets.enabled }}
          envFrom:
          - secretRef:
              name: {{ include "omnia-feed.fullname" . }}-ext-secret
          {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ include "omnia-feed.fullname" . -}}-gofer-cm
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
