apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rpc-router.fullname" . }}-config
data:
  dshackle.yaml: |
    version: v1
    port: {{ .Values.service.ports.grpc.port }}
    host: 0.0.0.0

    {{- if .Values.dshackle.compression }}
    compression:
    {{- toYaml .Values.dshackle.compression | nindent 6 }}
    {{- end }}

    monitoring:
      enabled: {{ .Values.dshackle.metrics.enabled }}
      jvm: {{ .Values.dshackle.metrics.jvm | default false }}
      extended: {{ .Values.dshackle.metrics.extended | default false }}
      prometheus:
        enabled: true
        bind: {{ .Values.dshackle.metrics.bind | default "127.0.0.1" }}
        port: {{ .Values.service.ports.metrics.port | default 8081 }}
        path: {{ .Values.dshackle.metrics.path | default "/metrics" }}

    health:
      port: {{ .Values.service.ports.health.port  | default 8082 }}
      host: {{ .Values.dshackle.health.host | default "127.0.0.1" }}
      path: {{ .Values.dshackle.health.path | default "/health" }}
      blockchains:
        {{- range .Values.dshackle.routes }}
        - chain: {{ .blockchain }}
          min-available: 1
        {{- end }}

    accessLog:
      enabled: {{ .Values.dshackle.accessLog }}

    {{- if .Values.redis.enabled }}
    cache:
      redis:
        enabled: true
        host: {{ .Release.Name }}-redis-master
        port: 6379
        db: 0
        password: {{ .Values.redis.auth.password }}
    {{- end }}

    proxy:
      host: 0.0.0.0
      port: {{ .Values.service.ports.proxy.port }}
      routes:
     {{- range .Values.dshackle.routes }}
        - id: {{ .id }}
          blockchain: {{ .blockchain }}
     {{- end }}
    cluster:
      include: "upstreams.yaml"
    signed-response:
      enabled: {{ .Values.dshackle.signedResponse | default false }}
  upstreams.yaml: |
    version: v1

    cluster:
      upstreams:
    {{- .Values.dshackle.upstreams | nindent 8 }}
