apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rpc-router.fullname" . }}-config
data:
  dshackle.yaml: |
    version: v1
    port: {{ .Values.service.ports.grpc.port }}
    host: 0.0.0.0

    {{- if .Values.dshackle.compression }}
    compression:
    {{- toYaml .Values.dshackle.compression | nindent 6 }}
    {{- end }}

    monitoring:
      enabled: {{ .Values.dshackle.metrics }}

    accessLog:
      enabled: {{ .Values.dshackle.accessLog }}

    {{- if .Values.redis.enabled }}
    cache:
      redis:
        enabled: true
        host: {{ .Release.Name }}-redis-master
        port: 6379
        db: 0
        password: {{ .Values.redis.auth.password }}
    {{- end }}

    proxy:
      host: 0.0.0.0
      port: {{ .Values.service.ports.proxy.port }}
      routes:
     {{- range .Values.dshackle.routes }}
        - id: {{ .id }}
          blockchain: {{ .blockchain }}
     {{- end }}
    cluster:
      upstreams:
    {{- .Values.dshackle.upstreams | nindent 8 }}
    signed-response:
      enabled: {{ .Values.dshackle.signedResponse | default false }}
