apiVersion: v2
appVersion: 0.6.1
description: A Helm chart for deploying an AutoScalingRunnerSet
home: https://github.com/actions/dev-arc
maintainers:
- name: actions
  url: https://github.com/actions
name: gha-runner-scale-set
sources:
- https://github.com/actions/dev-arc
type: application
version: 0.6.1
