apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "validator.serviceAccountName" . }}-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "validator.serviceAccountName" . }}-clusterrole
subjects:
- kind: ServiceAccount
  name: {{ include "validator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
