apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "validator.fullname" . }}
  labels:
    {{- include "validator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ghost.replicaCount }}
  selector:
    matchLabels:
      {{- include "validator.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-scripts.yaml") . | sha256sum }}
      {{- with .Values.ghost.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "validator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.ghost.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      serviceAccountName: {{ include "validator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.ghost.podSecurityContext | nindent 8 }}

      {{- if .Values.ghost.service.type | quote | eq "NodePort" }}
      initContainers:
        - name: init-public-ip
          image: bitnami/kubectl:latest
          command: ["/bin/bash", "-c"]
          args:
            - /scripts/get-ips.sh
          volumeMounts:
            - name: scripts
              mountPath: /scripts/get-ips.sh
              subPath: get-ips.sh
      {{- end }}

      containers:
        - name: ghost
          {{- include "ghost.container" (dict "ghost" .Values.ghost "chartName" .Chart.Name "releaseName" .Release.Name "chartVersion" .Chart.AppVersion) | nindent 8 }}
        - name: ghost2
          {{- include "ghost.container" (dict "ghost" .Values.ghost2 "chartName" .Chart.Name "releaseName" .Release.Name "chartVersion" .Chart.AppVersion) | nindent 8 }}

      {{- if .Values.ghost.service.type | quote | eq "NodePort" }}
      volumes:
        - name: scripts
          configMap:
            name: {{ include "validator.fullname" . }}-scripts
            defaultMode: 0755
      {{- end }}

      {{- with .Values.ghost.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.ghost.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.ghost.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
