apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "validator.serviceAccountName" . }}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "validator.serviceAccountName" . }}-role

subjects:
- kind: ServiceAccount
  name: {{ include "validator.serviceAccountName" . }}-serviceaccount
