apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "validator.fullname" . }}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "validator.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "validator.fullname" . }}-serviceaccount
