apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "validator.serviceAccountName" . }}-role

rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "services"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["{{ include "validator.fullname" . }}-scripts"]
  verbs: ["create","delete","get","list","patch","update","watch"]
