{{- if .Values.global.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "validator.fullname" . }}-metrics
  annotations:
  {{- with .Values.ghost.service.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "validator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: {{ .Values.global.metrics.port }}
      protocol: TCP
      targetPort: {{ .Values.global.metrics.port }}
  selector:
    {{- include "validator.selectorLabels" . | nindent 4 }}
{{- end }}