apiVersion: v1
kind: Service
metadata:
  name: {{ include "validator.fullname" . }}-vao
  annotations:
  {{- with .Values.vao.service.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "validatorVao.labels" . | nindent 4 }}
spec:
  type: {{ .Values.vao.service.type }}
  ports:
    {{- range $key, $val := .Values.vao.service.ports }}
    - port: {{ $val.port }}
      targetPort: {{ $val.port }}
      protocol: {{ $val.protocol }}
      name: {{ $key }}
    {{- end }}
  selector:
    {{- include "validatorVao.selectorLabels" . | nindent 4 }}
