{{- if eq (default "false" .Values.global.serviceAccount.create) "true" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "validator.serviceAccountName" . }}
  labels:
    {{- include "validator.labels" . | nindent 4 }}
  {{- with .Values.global.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
