apiVersion: tor.k8s.torproject.org/v1alpha2
kind: OnionService
metadata:
  name: {{ include "validator.fullname" . }}
  labels:
    {{- include "validator.labels" . | nindent 4 }}
spec:
  version: 3
  rules:
    - port:
        number: 8888
      backend:
        service:
          name: {{ include "validator.fullname" . }}
          port:
            number: {{ .Values.ghost.service.ports.webapi.port }}
  extraConfig: |
    HiddenServicePort 9999 ghost-metrics:9090
