automountServiceAccountToken: false

extraContainers:
  - name: fire-drill
    image: ghcr.io/chronicleprotocol/gofer:0.61@sha256:3915d2e41e041ea8aaba26149c48c4290de9df88f5aed6c271702d90ecb27e4c
    args:
      - fire-drill
    volumeMounts:
      - name: fire-drill-namespace
        mountPath: /var/run/chronicle/fire-drill
        readOnly: true

extraVolumes:
  - name: fire-drill-namespace
    downwardAPI:
      items:
        - path: namespace
          fieldRef:
            fieldPath: metadata.namespace
