# Default values for hyperliquid.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# node configuration
node:
  repository:
    image: ""
    tag: ""
  persistence:
    hl_data:
      # Storage class to use for PVCs
      # storageClass: "-" means use default
      # storageClass: "" means do not specify
      # storageClass: "foo" means use that storageClass
      storageClass: '-'
      size: 1Gi
      accessMode:
        - ReadWriteOnce
      enabled: true
  replicas: 1

  nodeSelector: {}
  # Resources allows you to specify the resource requests and limits for a service.
  # Resources are used to specify the amount of CPU and memory that
  # a container needs.
  #
  # e.g.
  # resources:
  #   requests:
  #     memory: "64Mi"
  #     cpu: "250m"
  #   limits:
  #     memory: "128Mi"
  #     cpu: "500m"
resources:
  # imagePullPolicy allows you to specify a policy to cache or always pull an image.
  # You must provide a string value with one of the following values:
  # - Always       -> will always pull the image
  # - Never        -> will never pull the image, the image should be present on the node
  # - IfNotPresent -> will pull the image only if it is not present on the node
  imagePullPolicy: IfNotPresent
  serviceAccount: ""

  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# pruner configuration
pruner:
  repository:
    image: ""
    tag: ""
  persistence:
    hl_data:
      # Storage class to use for PVCs
      # storageClass: "-" means use default
      # storageClass: "" means do not specify
      # storageClass: "foo" means use that storageClass
      storageClass: '-'
      size: 1Gi
      accessMode:
        - ReadWriteOnce
      enabled: true

  replicas: 1

  nodeSelector: {}
  # Resources allows you to specify the resource requests and limits for a service.
  # Resources are used to specify the amount of CPU and memory that
  # a container needs.
  #
  # e.g.
  # resources:
  #   requests:
  #     memory: "64Mi"
  #     cpu: "250m"
  #   limits:
  #     memory: "128Mi"
  #     cpu: "500m"
  # key: pruner.resources
  resources: {}
  # imagePullPolicy allows you to specify a policy to cache or always pull an image.
  # You must provide a string value with one of the following values:
  # - Always       -> will always pull the image
  # - Never        -> will never pull the image, the image should be present on the node
  # - IfNotPresent -> will pull the image only if it is not present on the node
  imagePullPolicy: IfNotPresent
  serviceAccount: ""

# imagePullSecrets allows you to specify a name of an image pull secret.
# You must provide a list of object with the name field set to the name of the
# e.g.
# pullSecrets:
# - name: regcred
# You are, for now, responsible for creating the secret.
pullSecrets: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

tolerations: []

affinity: {}
