# Default values for arbitrum.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/celestiaorg/nitro
  pullPolicy: IfNotPresent
  tag: "v3.5.5"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

settings:
    nodeType: light
    network: "celestia"
    # -- home directory for the celestia-node, defaults to /home/celestia
    home: "/home/celestia"

    ## A secret must be available in the cluster with the following format:
    ## - name: <secret-name>
    ## - items:
    ##     - key: my_celes_key_info
    ##     - key: uid
    ##     - key: address
    ##     - key: NJ3XILLTMVRXEZLUFZVHO5A
    ##     - key: OAZHALLLMV4Q
    secret:
      enabled: true
      # -- name of the secret, it must be set
      name: SET_IT
    ws:
      tls:
        enabled: false
        ## A secret must be available in the cluster with the following format:
        ## - name: <secret-name>
        ## - items:
        ##     - key: tls.cert
        ##     - key: tls.key
        secret:
          name: SET_IT
  config:
    light:
      configtoml:
        Node:
          StartupTimeout: 20s
          ShutdownTimeout: 20s
        Core:
          IP: ""
          Port: "9090"
          TLSEnabled: false
          XTokenPath: ""
        State:
          DefaultKeyName: my_celes_key
          DefaultBackendName: test
          EstimatorAddress: ""
          EnableEstimatorTLS: false
        P2P:
          ListenAddresses:
            - /ip4/0.0.0.0/udp/2121/quic-v1/webtransport
            - /ip6/::/udp/2121/quic-v1/webtransport
            - /ip4/0.0.0.0/udp/2121/quic-v1
            - /ip6/::/udp/2121/quic-v1
            - /ip4/0.0.0.0/udp/2121/webrtc-direct
            - /ip6/::/udp/2121/webrtc-direct
            - /ip4/0.0.0.0/tcp/2121
            - /ip6/::/tcp/2121
          AnnounceAddresses: []
          NoAnnounceAddresses:
            - /ip4/127.0.0.1/udp/2121/quic-v1/webtransport
            - /ip4/0.0.0.0/udp/2121/quic-v1/webtransport
            - /ip6/::/udp/2121/quic-v1/webtransport
            - /ip4/0.0.0.0/udp/2121/quic-v1
            - /ip4/127.0.0.1/udp/2121/quic-v1
            - /ip6/::/udp/2121/quic-v1
            - /ip4/0.0.0.0/udp/2121/webrtc-direct
            - /ip4/127.0.0.1/udp/2121/webrtc-direct
            - /ip6/::/udp/2121/webrtc-direct
            - /ip4/0.0.0.0/tcp/2121
            - /ip4/127.0.0.1/tcp/2121
            - /ip6/::/tcp/2121
          MutualPeers: []
          PeerExchange: false
          ConnManager:
            Low: 50
            High: 100
            GracePeriod: 1m0s
        RPC:
          Address: localhost
          Port: "26658"
          SkipAuth: false
        Gateway:
          Address: localhost
          Port: "26659"
          Enabled: false
        Share:
          BlockStoreCacheSize: 128
          UseShareExchange: true
          EDSStoreParams:
            RecentBlocksCacheSize: 10
          ShrExEDSParams:
            ServerReadTimeout: 5s
            ServerWriteTimeout: 1m0s
            HandleRequestTimeout: 1m0s
            ConcurrencyLimit: 10
            BufferSize: 32768
          ShrExNDParams:
            ServerReadTimeout: 5s
            ServerWriteTimeout: 1m0s
            HandleRequestTimeout: 1m0s
            ConcurrencyLimit: 10
          PeerManagerParams:
            PoolValidationTimeout: 2m0s
            PeerCooldown: 3s
            GcInterval: 30s
            EnableBlackListing: false
          LightAvailability:
            SampleAmount: 16
          Discovery:
            PeersLimit: 5
            AdvertiseInterval: 1h0m0s
        Header:
          TrustedHash: ""
          TrustedPeers: []
          Store:
            StoreCacheSize: 512
            IndexCacheSize: 2048
            WriteBatchSize: 512
          Syncer:
            TrustingPeriod: 336h0m0s
          Server:
            WriteDeadline: 8s
            ReadDeadline: 1m0s
            RangeRequestTimeout: 10s
          Client:
            MaxHeadersPerRangeRequest: 64
            RangeRequestTimeout: 8s
        DASer:
          SamplingRange: 100
          ConcurrencyLimit: 16
          BackgroundStoreInterval: 10m0s
          SampleFrom: 1
          SampleTimeout: 2m40s
        Pruner:
          EnableService: false

  # -- Container ports for the node
  containerPorts:
    # -- P2P container port, 2121 by default
    p2p: 2121
    # -- WebSocket container port, 2122 by default
    ws: 2122
    # -- REST container port, 26659 by default
    rest: 26659
    # -- RPC container port, 26658 by default
    rpc: 26658
    # -- Profiling container port, 6060 by default
    profiling: 6060
    # -- Prometheus container port, 8890 by default
    prometheus: 8890

  # -- Enable hostPort for the node
  #enableHostPort: true

  extraArgs:
    - --metrics
    - --metrics.tls=false
    - --p2p.metrics

  metrics:
    enabled: true
    serverAddr: {}
    serverPort: {}
    serverUpdateInterval: {}


serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  labels: {}
  annotations: {}
    # service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
  ports:
    rpc:
      port: 8547
      protocol: TCP
    ws:
      port: 8548
      protocol: TCP
    metrics:
      port: 6070
      protocol: TCP
    sequencer:
      port: 9642
      protocol: TCP

probes:
  enabled: false

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

persistence:
  # -- Uses an EmptyDir when not enabled
  enabled: false
  # -- Use an existing PVC when persistence.enabled
  existingClaim: null
  # -- Access mode for the volume claim template
  accessModes:
  - ReadWriteOnce
  # -- Requested size for volume claim template
  size: 3Ti
  # -- Use a specific storage class
  # E.g 'local-path' for local storage to achieve best performance
  # Read more (https://github.com/rancher/local-path-provisioner)
  storageClassName: null
  # -- Annotations for volume claim template
  annotations: {}
  # -- Selector for volume claim template
  selector: {}
  #   matchLabels:
  #     app.kubernetes.io/name: something

serviceMonitor:
  # -- If true, a ServiceMonitor CRD is created for a prometheus operator
  # https://github.com/coreos/prometheus-operator
  enabled: false
  # -- Path to scrape
  path: /debug/metrics
  # -- Alternative namespace for ServiceMonitor
  namespace: null
  # -- Additional ServiceMonitor labels
  labels: {}
  # -- Additional ServiceMonitor annotations
  annotations: {}
  # -- ServiceMonitor scrape interval
  interval: 1m
  # -- ServiceMonitor scheme
  scheme: http
  # -- ServiceMonitor TLS configuration
  tlsConfig: {}
  # -- ServiceMonitor scrape timeout
  scrapeTimeout: 30s
  # -- ServiceMonitor relabelings
  relabelings: []

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

tolerations: []

nodeSelector: {}

affinity: {}
