kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ include "oracle-suite.fullname" . }}-spire
data:
    config.json: |-
      {{ .Files.Glob "my-config.json" | indent 2}}
data:
  {{-/* Note, indent of only two spaces */}}
  config.json: |-
{{ .Files.Get "gofer.json" | indent 4 }}